/**
 * Configuracion de los servicios web que consume la aplicacion.
 *
 * Cada modulo declara su ruta, sus filtros y como presentar los datos,
 * de modo que una sola pantalla de listado sirve para todos.
 */
export const URL_BASE = 'https://dannurda.alwaysdata.net/api';
export const TIEMPO_LIMITE = 15000;

export const MODULOS = {
  espacios: {
    id: 'espacios',
    nombre: 'Espacios',
    icono: 'business-outline',
    ruta: '/espacios/',
    descripcion: 'Salas, oficinas y escritorios del coworking',
    clave: 'id_espacio',
    parametroFiltro: 'estado',
    filtros: [
      { valor: '', texto: 'Todos' },
      { valor: 'DISPONIBLE', texto: 'Disponibles' },
      { valor: 'MANTENIMIENTO', texto: 'Mantenimiento' },
      { valor: 'INACTIVO', texto: 'Inactivos' },
    ],
    titulo: (r) => `${r.codigo} · ${r.nombre}`,
    subtitulo: (r) => `${r.tipo_espacio_nombre} · ${r.ubicacion}`,
    valor: (r) => `$${r.tarifa_hora}`,
    etiquetaValor: 'por hora',
    insignia: (r) => r.estado_texto,
    colorInsignia: (r) => (r.estado === 'DISPONIBLE' ? 'marca' : 'alerta'),
    resumen: [
      { clave: 'Capacidad', valor: (r) => `${r.capacidad} personas` },
      { clave: 'Tarifa por hora', valor: (r) => `$${r.tarifa_hora}` },
      { clave: 'Estado', valor: (r) => r.estado_texto },
    ],
  },

  reservas: {
    id: 'reservas',
    nombre: 'Reservas',
    icono: 'calendar-outline',
    ruta: '/reservas/',
    descripcion: 'Reservas registradas en el sistema',
    clave: 'id_reserva',
    parametroFiltro: 'estado',
    filtros: [
      { valor: '', texto: 'Todas' },
      { valor: 'CONFIRMADA', texto: 'Confirmadas' },
      { valor: 'PENDIENTE', texto: 'Pendientes' },
      { valor: 'COMPLETADA', texto: 'Completadas' },
      { valor: 'CANCELADA', texto: 'Canceladas' },
    ],
    titulo: (r) => `${r.codigo} · ${r.espacio_nombre}`,
    subtitulo: (r) => r.cliente_nombre,
    valor: (r) => `$${r.total}`,
    etiquetaValor: 'total',
    insignia: (r) => r.estado_texto,
    colorInsignia: (r) =>
      r.estado === 'CONFIRMADA' ? 'marca' : r.estado === 'CANCELADA' ? 'error' : 'alerta',
    resumen: [
      { clave: 'Fecha', valor: (r) => r.fecha },
      { clave: 'Horario', valor: (r) => `${(r.hora_inicio || '').slice(0, 5)} a ${(r.hora_fin || '').slice(0, 5)}` },
      { clave: 'Personas', valor: (r) => `${r.numero_personas}` },
      { clave: 'Saldo pendiente', valor: (r) => `$${r.saldo_pendiente}` },
    ],
  },

  clientes: {
    id: 'clientes',
    nombre: 'Clientes',
    icono: 'people-outline',
    ruta: '/clientes/',
    descripcion: 'Personas y empresas registradas',
    clave: 'id_cliente',
    parametroFiltro: '',
    filtros: [],
    titulo: (r) => r.nombre_completo,
    subtitulo: (r) => `${r.cedula} · ${r.correo}`,
    valor: (r) => `${r.total_reservas}`,
    etiquetaValor: 'reservas',
    insignia: (r) => r.tipo_cliente_texto,
    colorInsignia: (r) => (r.activo ? 'marca' : 'textoSuave'),
    resumen: [
      { clave: 'Telefono', valor: (r) => r.telefono },
      { clave: 'Empresa', valor: (r) => r.empresa || 'Sin empresa' },
      { clave: 'Estado', valor: (r) => (r.activo ? 'Activo' : 'Inactivo') },
    ],
  },

  pagos: {
    id: 'pagos',
    nombre: 'Pagos',
    icono: 'card-outline',
    ruta: '/pagos/',
    descripcion: 'Abonos registrados sobre las reservas',
    clave: 'id_pago',
    parametroFiltro: 'metodo',
    filtros: [
      { valor: '', texto: 'Todos' },
      { valor: 'EFECTIVO', texto: 'Efectivo' },
      { valor: 'TARJETA', texto: 'Tarjeta' },
      { valor: 'TRANSFERENCIA', texto: 'Transferencia' },
    ],
    titulo: (r) => `${r.reserva_codigo} · ${r.cliente_nombre}`,
    subtitulo: (r) => `${r.metodo_pago_texto} · ${r.fecha_pago}`,
    valor: (r) => `$${r.monto}`,
    etiquetaValor: 'monto',
    insignia: (r) => r.estado_texto,
    colorInsignia: (r) => (r.estado === 'CONFIRMADO' ? 'marca' : 'alerta'),
    resumen: [
      { clave: 'Metodo', valor: (r) => r.metodo_pago_texto },
      { clave: 'Referencia', valor: (r) => r.referencia || 'Sin referencia' },
      { clave: 'Estado', valor: (r) => r.estado_texto },
    ],
  },

  tipos: {
    id: 'tipos',
    nombre: 'Tipos de espacio',
    icono: 'layers-outline',
    ruta: '/tipos-espacio/',
    descripcion: 'Clasificacion de las areas del coworking',
    clave: 'id_tipo_espacio',
    parametroFiltro: '',
    filtros: [],
    titulo: (r) => r.nombre,
    subtitulo: (r) => r.descripcion || 'Sin descripcion',
    valor: (r) => `${r.total_espacios}`,
    etiquetaValor: 'espacios',
    insignia: (r) => (r.activo ? 'Activo' : 'Inactivo'),
    colorInsignia: (r) => (r.activo ? 'marca' : 'textoSuave'),
    resumen: [
      { clave: 'Espacios registrados', valor: (r) => `${r.total_espacios}` },
      { clave: 'Estado', valor: (r) => (r.activo ? 'Activo' : 'Inactivo') },
    ],
  },

  servicios: {
    id: 'servicios',
    nombre: 'Servicios',
    icono: 'cube-outline',
    ruta: '/servicios/',
    descripcion: 'Extras que se agregan a una reserva',
    clave: 'id_servicio',
    parametroFiltro: '',
    filtros: [],
    titulo: (r) => r.nombre,
    subtitulo: (r) => r.descripcion || 'Sin descripcion',
    valor: (r) => `$${r.precio}`,
    etiquetaValor: 'precio',
    insignia: (r) => (r.activo ? 'Activo' : 'Inactivo'),
    colorInsignia: (r) => (r.activo ? 'marca' : 'textoSuave'),
    resumen: [
      { clave: 'Precio unitario', valor: (r) => `$${r.precio}` },
      { clave: 'Estado', valor: (r) => (r.activo ? 'Activo' : 'Inactivo') },
    ],
  },
};

export const NOMBRES_CAMPOS = {
  id_espacio: 'ID', id_reserva: 'ID', id_cliente: 'ID', id_pago: 'ID',
  id_tipo_espacio: 'ID', id_servicio: 'ID',
  codigo: 'Codigo', nombre: 'Nombre', descripcion: 'Descripcion',
  tipo_espacio: 'ID del tipo', tipo_espacio_nombre: 'Tipo de espacio',
  ubicacion: 'Ubicacion', capacidad: 'Capacidad', tarifa_hora: 'Tarifa por hora',
  estado: 'Estado (codigo)', estado_texto: 'Estado',
  cliente: 'ID del cliente', cliente_nombre: 'Cliente', nombre_completo: 'Nombre completo',
  cedula: 'Cedula', correo: 'Correo', telefono: 'Telefono', empresa: 'Empresa',
  tipo_cliente: 'Tipo (codigo)', tipo_cliente_texto: 'Tipo de cliente',
  activo: 'Activo', total_reservas: 'Total de reservas', total_espacios: 'Total de espacios',
  espacio: 'ID del espacio', espacio_codigo: 'Codigo del espacio', espacio_nombre: 'Espacio',
  fecha: 'Fecha', hora_inicio: 'Hora de inicio', hora_fin: 'Hora de fin', horas: 'Horas',
  numero_personas: 'Numero de personas', observaciones: 'Observaciones',
  subtotal_espacio: 'Subtotal del espacio', subtotal_servicios: 'Subtotal de servicios',
  total: 'Total', total_pagado: 'Total pagado', saldo_pendiente: 'Saldo pendiente',
  reserva: 'ID de la reserva', reserva_codigo: 'Reserva', fecha_pago: 'Fecha del pago',
  monto: 'Monto', metodo_pago: 'Metodo (codigo)', metodo_pago_texto: 'Metodo de pago',
  referencia: 'Referencia', precio: 'Precio',
};
